---
apiVersion: v1
kind: Namespace
metadata:
  name: guppyecho
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  namespace: guppyecho
  name: guppyecho
spec:
  selector:
    app: guppyecho
  ports:
    - name: grpc
      port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guppyecho
  name: guppyecho
  labels:
    app: guppyecho
  annotations:
    transflect.cash.squareup.com/port: "9090"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guppyecho
  template:
    metadata:
      labels:
        app: guppyecho
    spec:
      containers:
        - name: guppyecho
          image: julia/echo:v0.0.4
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: guppyecho
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: guppyecho.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guppyecho
            port:
              number: 9090
