---
apiVersion: v1
kind: Namespace
metadata:
  name: routeguide
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  namespace: routeguide
  name: routeguide
spec:
  selector:
    app: routeguide
  ports:
    - name: grpc
      port: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: routeguide
  name: routeguide
  labels:
    app: routeguide
  annotations:
    transflect.cash.squareup.com/port: "9090"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: routeguide
  template:
    metadata:
      labels:
        app: routeguide
    spec:
      containers:
        - name: routeguide
          image: julia/routeguide:v0.0.3
          ports:
            - name: grpc
              protocol: TCP
              containerPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: routeguide
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - host: routeguide.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: routeguide
            port:
              number: 9090
