---
apiVersion: v1
kind: Namespace
metadata:
  name: transflect
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: transflect
  name: transflect
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: transflect
  name: transflect
  labels:
    app: transflect
spec:
  selector:
    matchLabels:
      app: transflect
  template:
    metadata:
      labels:
        app: transflect
    spec:
      serviceAccountName: transflect
      automountServiceAccountToken: true
      containers:
        - name: transflect
          # image: cashapp/transflect # Use image from Dockerhub
          image: k3d-registry.transflect.local:420/transflect:latest
          imagePullPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transflect
rules:
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployment
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - networking.istio.io
    resources:
      - envoyfilters
    verbs:
      - create
      - delete
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: transflect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: transflect
subjects:
  - kind: ServiceAccount
    namespace: transflect
    name: transflect
