name: ci/cd

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./bin/hermit env --raw >> $GITHUB_ENV
    - run: make ci

  release:
    runs-on: ubuntu-latest
    needs: [ ci ]
    if: github.event_name == 'push' # only run on push to master
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow --tags
    - run: ./bin/hermit env --raw >> $GITHUB_ENV
    - run: make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  slack-on-fail:
    runs-on: ubuntu-latest
    needs: [ci, release]
    if: always() && github.event_name == 'push' && (needs.ci.result == 'failure' || needs.release.result == 'failure')
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/workflows/slack-notify.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_TEXT: <!subteam^S025MNP8G67> # @transflect-owners
